### PR TITLE
Allow forecast for a single day

### PR DESCRIPTION
**Pull request by smalldave**
As it stands the minimum number of days you can get a forecast for is 2.

### CODE REVIEW

**Comment by jessfraz** [comment]
Isn't a single day the same as current?

**Comment by smalldave** [comment]
Possibly but currently the value 2 gives you the weather now plus 2 days of forecast. As 1 is ignored I can't get the current weather plus tomorrow's forecast.

**Comment by jessfraz** [comment]
Oh cool gotcha was just curious

**Comment by smalldave** [comment]
Small laptop screen, hence other PR :)

**Pull request merged**
